site_name: Everest-models
repo_url: https://github.com/equinor/everest-models
site_description: Forward models and workflows to be used with Ert and Everest
site_author: Equinor and TNO
edit_uri: edit/main/docs
repo_name: equinor/everest-models

nav:
  - Home: index.md
  - tutorials.md
  - How-To Guides:
    - contribute/contribute.md
    - Add Template: https://fmu-docs.equinor.com/docs/everest/tutorial/everest_templating.html#pipelining-forward-models
    - Well Order Optimization: https://fmu-docs.equinor.com/docs/everest/tutorial/well_order_optimisation.html#forward-models
    - Well Rate Optimization: https://fmu-docs.equinor.com/docs/everest/tutorial/well_rate_optimisation.html#forward-models
    - Well Selection Optimization: https://fmu-docs.equinor.com/docs/everest/tutorial/well_selection.html#forward-models
  - Reference:
      - Jobs:
        - Add Templates: reference/add_templates/reference.md
        - Drill Date Planner: reference/drill_date_planner/reference.md
        - Drill Planner: reference/drill_planner/reference.md
        - Compute Economics: reference/compute_economics/reference.md
        - Extract Summary Date: reference/extract_summary_data/reference.md
        - Interpret Well Drill: reference/interpret_well_drill/reference.md
        - Net Present Value: reference/npv/reference.md
        - Recovery Factor: reference/rf/reference.md
        - Schmerge: reference/schmerge/reference.md
        - Select Wells: reference/select_wells/reference.md
        - Stea: reference/stea/reference.md
        - Strip Dates: reference/strip_dates/reference.md
        - Well Constraints: reference/well_constraints/reference.md
        - Well Filter: reference/well_filter/reference.md
        - Well Trajectory: reference/well_trajectory/reference.md
      - Shared Functions:
        - Validators: reference/shared/validators.md
        - Models: reference/shared/models.md
        - Arguments: reference/shared/arguments.md
      - reference/hook.md
  - explanation.md

plugins:
  - search
  - mkdocstrings:

theme:
  name: material
  font:
    code: Fira Code
  features:
    - tabs: true
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - mdx_include:
      base_path: docs
  - codehilite
  - mdantic
  - admonition

extra:
  social:
    - icon: fontawesome/brands/slack
      link: https://join.slack.com/share/enQtNTE1MTAwNTI0NDg5Ny03ZmNmNzVmODQ2MGEzNjdmMDI5YTM5OWYyZWVlMjQ4OGU3NDgyNmFmZDNlZTZiZmYzMTg1MzA3OGI3NmZjMGE4
    - icon: fontawesome/brands/github
      link: https://github.com/equinor/everest-models/issues
      name: Issue Tracker

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
