#!/usr/bin/env python
import argparse
import logging
from functools import partial

from jobs.fm_drill_date_planner import tasks
from jobs.utils.io_utils import write_json_to_file
from jobs.utils.validators import is_writable, valid_json_file

logger = logging.getLogger(__name__)


def parse_arguments(args):
    parser = argparse.ArgumentParser(
        description="Calculate and write drill times from scaled controls."
    )
    parser.add_argument(
        "-i",
        "--input",
        required=True,
        type=partial(valid_json_file, parser=parser),
        help="Wells file generated by Everest (wells.json).",
    )
    parser.add_argument(
        "-opt",
        "--optimizer",
        required=True,
        type=partial(valid_json_file, parser=parser),
        help="File containing information related to wells. The format is "
        "consistent with the wells.json file when running everest and can "
        "be used directly.",
    )
    parser.add_argument(
        "-b",
        "--bounds",
        required=True,
        type=float,
        metavar=["UPPER", "LOWER"],
        help="Upper and lower bounds of the controls.",
        nargs=2,
    )
    parser.add_argument(
        "-m",
        "--max-days",
        required=True,
        type=int,
        help="Maximum time interval in days.",
    )
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        type=partial(is_writable, parser=parser),
        help="Output file: input for drill planner job.",
    )
    return parser.parse_args(args)


def main_entry_point(args=None):
    args = parse_arguments(args)

    output = tasks.drill_date_planner(
        args.input, args.optimizer, args.bounds, args.max_days
    )

    if args.output:
        logger.info("Writing results to {}".format(args.output))
        write_json_to_file(output, args.output)


if __name__ == "__main__":
    main_entry_point()
