# -c/--config specification:
# <REPLACE> is a REQUIRED field that needs replacing

<STRING>:
  <INTEGER>:

    # Required: True
    phase:

      # Datatype: [string]
      # Required: False
      # Default: null
      options:
        - <REPLACE>

      # Datatype: string
      # Choices: WATER, GAS, OIL
      # Required: False
      # Default: null
      value: null

    # Required: False
    # Default: value=None
    rate:

      # Datatype: number,
      # Required: False
      # Default: null
      value: <REPLACE>

    # Required: False
    # Default: value=None
    duration:

      # Datatype: number,
      # Required: False
      # Default: null
      value: <REPLACE>
