---
arguments: --config/-c
fields:
   string:
      integer:
         duration:
            max: {required: false, type: number}
            min: {required: false, type: number}
            value: {required: false, type: number}
         phase:
            options:
            - choices: [WATER, GAS, OIL]
              type: string
            value:
               choices: [WATER, GAS, OIL]
               type: string
         rate:
            max: {required: false, type: number}
            min: {required: false, type: number}
            value: {required: false, type: number}
...
---
arguments: [--rate-constraints/-rc, --phase-constraints/-pc, --duration-constraints/-dc]
fields:
   string: {integer: float}
...
---
arguments: -i/--input
fields:
- completion_date: {format: date, required: false, type: string}
  drill_time: {required: false, type: integer}
  name: {required: true, type: string}
  ops: [OperationType]
  readydate: {format: date, required: false, type: string}
...
