# -c/--config specification:
# '...' are REQUIRED fields that needs replacing


# Datatype: {string: [CurrencyRate map]}
# Required: True
prices:
  <string>:
  -

      # Datatype: number
      # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
      # Required: True
    value: '...'  # ← REPLACE

      # Datatype: string
      # Examples: a string value
      # Required: False
      # Default: null
    currency: null

      # Datatype: date
      # Examples: 2024-01-31, 2024-01-31T11:06
      # Required: True
    date: '...'  # ← REPLACE

# Datatype: integer
# Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
# Required: False
# Default: 1
multiplier: 1

# Datatype: integer
# Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
# Required: False
# Default: 1
default_exchange_rate: 1

# Datatype: number
# Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
# Required: False
# Default: 0.08
default_discount_rate: 0.08

# Datatype: Dates map
# Required: False
dates:

  # Datatype: date
  # Examples: 2024-01-31, 2024-01-31T11:06
  # Required: False
  # Default: null
  start_date: null

  # Datatype: date
  # Examples: 2024-01-31, 2024-01-31T11:06
  # Required: False
  # Default: null
  end_date: null

  # Datatype: date
  # Examples: 2024-01-31, 2024-01-31T11:06
  # Required: False
  # Default: null
  ref_date: null

# Datatype: {string: [CurrencyRate map]}
# Required: False
exchange_rates:
  <string>:
  -

      # Datatype: number
      # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
      # Required: True
    value: '...'  # ← REPLACE

      # Datatype: string
      # Examples: a string value
      # Required: False
      # Default: null
    currency: null

      # Datatype: date
      # Examples: 2024-01-31, 2024-01-31T11:06
      # Required: True
    date: '...'  # ← REPLACE

# Datatype: [CurrencyRate map]
# Required: False
discount_rates:
-

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: True
  value: '...'  # ← REPLACE

    # Datatype: string
    # Examples: a string value
    # Required: False
    # Default: null
  currency: null

    # Datatype: date
    # Examples: 2024-01-31, 2024-01-31T11:06
    # Required: True
  date: '...'  # ← REPLACE

# Datatype: [CurrencyRate map]
# Required: False
costs:
-

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: True
  value: '...'  # ← REPLACE

    # Datatype: string
    # Examples: a string value
    # Required: False
    # Default: null
  currency: null

    # Datatype: date
    # Examples: 2024-01-31, 2024-01-31T11:06
    # Required: True
  date: '...'  # ← REPLACE

# Datatype: [WellCost map]
# Required: False
well_costs:
-

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: True
  value: '...'  # ← REPLACE

    # Datatype: string
    # Examples: a string value
    # Required: False
    # Default: null
  currency: null

    # Datatype: string
    # Examples: a string value
    # Required: True
  well: '...' # ← REPLACE

# Datatype: [string]
# Required: True
summary_keys:
- '...'
