# -c/--config specification:
# <REPLACE> is a REQUIRED field that needs replacing


# Required: True
scales:

  # Datatype: number
  # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
  # Required: True
  x: <REPLACE>

  # Datatype: number
  # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
  # Required: True
  y: <REPLACE>

  # Datatype: number
  # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
  # Required: True
  z: <REPLACE>

  # Datatype: number
  # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
  # Required: False
  # Default: null
  k: null

# Required: True
references:

  # Datatype: number
  # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
  # Required: True
  x: <REPLACE>

  # Datatype: number
  # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
  # Required: True
  y: <REPLACE>

  # Datatype: number
  # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
  # Required: True
  z: <REPLACE>

  # Datatype: number
  # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
  # Required: False
  # Default: null
  k: null

# Required: True
interpolation: <REPLACE>

# Required: False
# Default: null
connections:

  # Datatype: resinsight
  # Required: True
  type: <REPLACE>

  # Datatype: date
  # Examples: 2024-01-31, 2024-01-31T11:06
  # Required: True
  date: <REPLACE>

  # Datatype: Path
  # Examples: /path/to/file.ext, /path/to/directory/
  # Required: True
  formations_file: <REPLACE>

  # Required: True
  perforations:
    -

      # Datatype: string
      # Examples: a string value
      # Required: True
      well: <REPLACE>

      # Required: False
      dynamic:
        -

          # Datatype: string
          # Examples: a string value
          # Required: True
          key: <REPLACE>

          # Datatype: number
          # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
          # Required: True
          min: <REPLACE>

          # Datatype: number
          # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
          # Required: True
          max: <REPLACE>

      # Required: False
      static:
        -

          # Datatype: string
          # Examples: a string value
          # Required: True
          key: <REPLACE>

          # Datatype: number
          # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
          # Required: True
          min: <REPLACE>

          # Datatype: number
          # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
          # Required: True
          max: <REPLACE>

      # Datatype: [integer]
      # Required: False
      formations:
        - <REPLACE>

# Required: False
platforms:
  -

    # Datatype: string
    # Examples: a string value
    # Required: True
    name: <REPLACE>

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: True
    x: <REPLACE>

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: True
    y: <REPLACE>

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: False
    # Default: null
    k: null

# Required: True
wells:
  -

    # Datatype: string
    # Examples: a string value
    # Required: True
    name: <REPLACE>

    # Datatype: string
    # Examples: a string value
    # Required: True
    group: <REPLACE>

    # Datatype: string
    # Choices: WATER, GAS, OIL
    # Required: True
    phase: <REPLACE>

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: False
    # Default: 0.0
    skin: 0.0

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: False
    # Default: 0.15
    radius: 0.15

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: False
    # Default: 4.0
    dogleg: 4.0

    # Datatype: number
    # Examples: .1, 1., 1, 1.0, 1.34E-5, 1.34e-5
    # Required: False
    # Default: 0.0
    cost: 0.0

    # Datatype: string
    # Examples: a string value
    # Required: False
    # Default: null
    platform: null

# Datatype: Path
# Examples: /path/to/file.ext, /path/to/directory/
# Required: False
# Default: null
eclipse_model: null

# Datatype: Path
# Examples: /path/to/file.ext, /path/to/directory/
# Required: False
# Default: null
resinsight_binary: null

# Datatype: Path
# Examples: /path/to/file.ext, /path/to/directory/
# Required: False
# Default: null
npv_input_file: null
