# -c/--config specification:
# '...' are REQUIRED fields that needs replacing


# Datatype: date
# Examples: 2024-01-31, 2024-01-31T11:06
# Required: True
start_date: '...'  # ← REPLACE

# Datatype: date
# Examples: 2024-01-31, 2024-01-31T11:06
# Required: True
end_date: '...'  # ← REPLACE

# Datatype: [Rig map]
# Required: True
rigs:
-

    # Datatype: string
    # Examples: a string value
    # Required: True
  name: '...'  # ← REPLACE

    # Datatype: [string]
    # Required: False
  wells:
  - '...'

    # Datatype: [Unavailability map]
    # Required: False
  unavailability:
  -

        # Datatype: date
        # Examples: 2024-01-31, 2024-01-31T11:06
        # Required: True
    start: '...'  # ← REPLACE

        # Datatype: date
        # Examples: 2024-01-31, 2024-01-31T11:06
        # Required: True
    stop: '...' # ← REPLACE

    # Datatype: [string]
    # Required: False
  slots:
  - '...'

    # Datatype: integer
    # Examples: 1, 1.34E5, 1.34e5
    # Required: False
    # Default: 0
  delay: 0

# Datatype: [Slot map]
# Required: False
slots:
-

    # Datatype: string
    # Examples: a string value
    # Required: True
  name: '...'  # ← REPLACE

    # Datatype: [string]
    # Required: False
  wells:
  - '...'

    # Datatype: [Unavailability map]
    # Required: False
  unavailability:
  -

        # Datatype: date
        # Examples: 2024-01-31, 2024-01-31T11:06
        # Required: True
    start: '...'  # ← REPLACE

        # Datatype: date
        # Examples: 2024-01-31, 2024-01-31T11:06
        # Required: True
    stop: '...' # ← REPLACE
