name: Test integration with ert
on:
  push:
    branches:
      - main
    tags: "*"
  pull_request:
  workflow_dispatch:

env:
  ERT_SHOW_BACKTRACE: 1

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Ubuntu dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libegl1 -y

      - uses: "actions/checkout@v5"
        with:
          fetch-depth: 0

      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml

      - name: "Install package"
        run: |
          pip install --upgrade pip
          pip install .[test,ert]
          pip install -U git+https://github.com/equinor/ert.git@main

      - name: Install flow
        run: |
          set -e
          sudo apt install software-properties-common
          sudo apt-add-repository ppa:opm/ppa
          sudo apt update
          sudo apt install mpi-default-bin
          sudo apt install libopm-simulators-bin python3-opm-common
          which flow
          flow --version

      - name: "Test package everest-models"
        run: |
          python -m pytest -sv -m "flow" --test-flow
